#!/bin/bash
# This script must run in control node 
# from vagrant host, vagrant ssh control

curl https://raw.githubusercontent.com/gbenselum/diversity_ansible_lab/master/hosts --output ~/inventory
sudo yum install python3
sudo pip3 install ansible ansible-lint
